spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:gdg_market.sqlite3
    username: root
    password: toor


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        naming:
          use-new-id-generator-mappings: false
        use_sql_comments: true
        format_sql: true
      globally_quoted_identifiers: true

  logging:
    level:
      org.springframework: DEBUG